owner: Shiroo-ai
repo: shiroo-uptime-monitor

assignees:
  - kdelfour

sites:
  # Applications
  - name: Shiroo App Production
    url: https://app.shiroo.ai
    slug: shiroo-app-production
    maxResponseTime: 1000
    assignees:
      - kdelfour
      - zokiasu
      - renaudcepre
  - name: Shiroo App Staging
    url: https://app.shiroo.staging.araiko.ai
    maxResponseTime: 1000
    slug: shiroo-app-staging

  # API
  - name: Shiroo API Production
    url: https://w1uco5w4y9.execute-api.eu-west-3.amazonaws.com/v1/
    maxResponseTime: 1000
    slug: shiroo-api-production
    assignees:
      - kdelfour
      - zokiasu
      - renaudcepre
  - name: Shiroo API Staging
    url: https://cwws8q8ex0.execute-api.eu-west-3.amazonaws.com/v1/
    maxResponseTime: 1000
    slug: shiroo-api-staging

  # Website
  - name: Shiroo website
    url: https://www.shiroo.ai/

  # OpenAI
  - name: Shiroo AI Chat Completions
    url: https://status.openai.com/api/v2/components/01JMXBRMFE6N2NNT7DG6XZQ6PW.json
    method: GET
    expectedStatusCodes: [200]
    maxResponseTime: 10000
    expectedBodyContains: '"status":"operational"'
  - name: Shiroo AI Responses
    url: https://status.openai.com/api/v2/components/01JP8CD9JR3HR6Y7G4Q75N4DVW.json
    method: GET
    expectedStatusCodes: [200]
    maxResponseTime: 10000
    expectedBodyContains: '"status":"operational"'
  - name: Shiroo AI Audio Transcriptions
    url: https://status.openai.com/api/v2/components/01JMXBRMFEKVBWKK82B44QFMCE.json
    method: GET
    expectedStatusCodes: [200]
    expectedBodyContains: '"status":"operational"'

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /shiroo-uptime-monitor
  logoUrl: https://cdn.prod.website-files.com/6710b572c4cfa11400efed52/67b4525e15d113de7ca28224_Shiroo%20Icon%20Without%20Text.png
  name: Shiroo
  themeUrl: https://shiroo-ai.github.io/shiroo-uptime-monitor/shiroo-theme.css
  introTitle: "Surveillance des environnements Shiroo.ai"
  introMessage: "Cette page vous permet de visualiser l'état des différents environnements de l'application Shiroo.ai, de suivre les incidents en cours ainsi que les maintenances prévues."
  navbar:
    - title: Status
      href: /shiroo-uptime-monitor
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
