# Change these first
owner: Shiroo.ai # Your GitHub organization or username, where this repository lives
repo: shiroo-uptime-monitor # The name of this repository

sites:
  - name: Shiroo staging
    url: https://app.shiroo.staging.araiko.ai
  - name: Shiroo production
    url: https://app.shiroo.ai

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /shiroo-uptime-monitor
  logoUrl: https://cdn.prod.website-files.com/6710b572c4cfa11400efed52/67b4525e15d113de7ca28224_Shiroo%20Icon%20Without%20Text.png
  name: Shiroo
  introTitle: "**Shiroo** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
