owner: Shiroo-ai
repo: shiroo-uptime-monitor

assignees:
  - kdelfour

sites:
  - name: Shiroo app production
    url: https://app.shiroo.ai
  - name: Shiroo app staging
    url: https://app.shiroo.staging.araiko.ai
  - name: Shiroo website
    url: https://www.shiroo.ai/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /shiroo-uptime-monitor
  logoUrl: https://cdn.prod.website-files.com/6710b572c4cfa11400efed52/67b4525e15d113de7ca28224_Shiroo%20Icon%20Without%20Text.png
  name: Shiroo
  # themeUrl: https://shiroo-ai.github.io/shiroo-uptime-monitor/shiroo-theme.css
  introTitle: "Surveillance des environnements Shiroo.ai"
  introMessage: "Cette page vous permet de visualiser l'état des différents environnements de l'application Shiroo.ai, de suivre les incidents en cours ainsi que les maintenances prévues."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
